apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hqoas-jdbc-demo
  kind: pipeline

namespace: hqoas-jdbc-demo

resources:
  - namespace.yaml
  - permissions.yaml
  - maven-pvc.yaml
  - build-task.yaml
  - maven-pipeline.yaml
  - maven-task.yaml
  - cleanup-workspace-task.yaml